name: Build FFmpeg

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libvpx-dev \
            yasm \
            pkg-config \
            libx264-dev

      - name: Configure and Build FFmpeg
        run: |
          ./configure \
            --pkg-config-flags="--static" \
            --extra-cflags="-I/usr/local/include" \
            --extra-ldflags="-L/usr/local/lib" \
            --extra-libs="-lpthread -lm" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libx264 \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvpx \
            --enable-filter=xfade \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --disable-doc \
            --disable-programs \
            --disable-ffplay

          make -j$(nproc)

          # Create redistributable directory
          mkdir -p ../ffmpeg-redistributable
          cp ffmpeg ../ffmpeg-redistributable/
          cp ffprobe ../ffmpeg-redistributable/

          # Create the tar.gz file
          cd ..
          tar -czvf ffmpeg-redistributable-$(date +%Y%m%d%H%M).tar.gz ffmpeg-redistributable

      - name: Create GitHub Release
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M)"  # Valid tag name
          RELEASE_NAME="FFmpeg Build $TAG_NAME"
          gh release create "$TAG_NAME" ffmpeg-redistributable-*.tar.gz --title "$RELEASE_NAME" --notes "Automated FFmpeg build."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
